/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        jogoVelha();
    }


    private static void jogoVelha(){

        Scanner teclado = new Scanner(System.in);

        while (teclado.hasNext()){
            String saida = teclado.nextLine();
            System.out.println(saida.charAt(0));

        }

        String linha = "\u2500";
        String cruz = "\u253C";
        String coluna = "\u2502";

        System.out.println("  "+ coluna + "  " +coluna +"\n" +
                linha + linha + cruz + linha + linha + cruz + linha + linha + "\n" +
                linha + linha + cruz + linha + linha + cruz + linha + linha + "\n" +
                "  " + coluna + "  " +coluna);
    }

    private static void terminalComArquivos(){
        int contador=0;
        Scanner leitor = new Scanner(System.in);

        while (leitor.hasNext()) {
            String linha = leitor.nextLine().toUpperCase();
            System.out.println(" " + contador + " " + linha);
            contador++;
        }
        leitor.close();
    }
}
