/*
 * This source file was generated by the Gradle 'init' task
 */
package aula24;

import main.java.aula24.Dimensao;
import main.java.aula24.Semfio;

public class App {
    

    public static void main(String[] args) {
        Dimensao dim = new Dimensao();
        Semfio semfio = new Semfio(0, "222", "Nokia", 200, dim, 2.4, 4, 6);

        System.out.println(semfio.imprimirDados());
    }
}
