/*
 * This source file was generated by the Gradle 'init' task
 */
package poo;

import poo.Batedeira;
import poo.Contador;
import poo.Disciplina;
import poo.Player;

public class App {
    
    public static void main(String[] args) {
        

        Contador contador = new Contador();

        System.out.println("Contador");

        contador.incrementarValor();
        System.out.println(contador.pegarValor());
        contador.atribuirValor(100);
        System.out.println(contador.pegarValor());
        

        Player player = new Player();

        System.out.println("Player");

        System.out.println(player.getAttackBase());
        System.out.println(player.getStamina());
        player.takeDamage(5);
        player.healYourself(10);
        System.out.println(player.getVida());

        System.out.println("Batedeira");

        Batedeira batedeira = new Batedeira();

        batedeira.novaVelocidade(20);
        batedeira.girar();
        System.out.println(batedeira.getPorcentagemMistura());

        System.out.println("Disciplina");

        Disciplina disciplina = new Disciplina("Programação Orientada a Objetos", "Emerson", 60, 2, 20, "POO");
        System.out.println(disciplina.getCargaTeorica());
        System.out.println(disciplina.getDisciplina());

        disciplina.toString();
    }

}
