/*
 * This source file was generated by the Gradle 'init' task
 */
package aula20;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

public class App {

    private Agenda agenda;

    private Scanner scan = new Scanner(System.in);
    

    public App(){
        agenda = new Agenda();
    }

    public void menu(){
      int teclado;  
      do{
          tabelaOpções();
            teclado = scan.nextInt();
            scan.nextLine();

            switch (teclado) {
                case 1:
                    criarContato();
                    break;
                case 2:
                    agenda.listar();
                    break;
                case 3:
                    acharContato();
                    break;
                case 4:
                    adicionarTelefone();
                    break;
                default:
                    break;
            }
        } while (teclado != 5);
        
    }

    private void tabelaOpções() {
        System.out.println("---------Menu----------");
        System.out.println("1 - Criar Contato");
        System.out.println("2 - ");
        System.out.println("3 - Achar Contatos");
        System.out.println("4 - Adicionar Telefone");
        System.out.println("5 - ");
    }

    private boolean criarContato(){
        System.out.println("---------Contato----------");
        System.out.print("Nome: ");
        String nome = scan.nextLine();
        System.out.print("Sobrenome: ");
        String sobrenome = scan.nextLine();
        System.out.print("Entre com a data (dd/mm/aaaa): ");
        String dataString = scan.nextLine();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(dataString, formato);

        Contato cont = new Contato(nome, sobrenome, data);

        agenda.addContato(cont);
        return true;
    }

    private void acharContato(){
      System.out.println("---------Achar Contatos----------");
      System.out.println("Digite o que se pede");
      System.out.print("Nome: ");
      String nome = scan.nextLine();
      System.out.print("Sobrenome: ");
      String sobrenome = scan.nextLine();
      Contato contatoachado = agenda.findContatos(nome, sobrenome);
      System.out.println(contatoachado);
    }

    private void adicionarTelefone(){
      System.out.println("---------Adicionar Telefone----------");
      System.out.println("Digite o que se pede");
      System.out.print("Rotulo: ");
      String rotulo = scan.nextLine();
      System.out.print("Valor: ");
      String valor = scan.nextLine();
      System.out.print("Indice: ");
      int indice = scan.nextInt();
      scan.nextLine();
      boolean status = agenda.addTelefone(rotulo, valor, indice);
      System.out.println(status);
    }

    public static void main(String[] args) {
        App app = new App();

        app.menu();
    }
}
