/*
 * This source file was generated by the Gradle 'init' task
 */
package aula20;

import java.util.Scanner;

public class App {

    private Scanner scan = new Scanner(System.in);
    

    public App(){

    }

    public void menu(){
        tabelaOpções();
    }

    private void tabelaOpções() {
        System.out.println("---------Menu----------");
        System.out.println("1 - ");
        System.out.println("2 - ");
        System.out.println("3 - ");
        System.out.println("4 - ");
        System.out.println("5 - ");
    }

    public static void main(String[] args) {
        App app = new App();

        app.menu();
    }
}
