/*
 * This source file was generated by the Gradle 'init' task
 */
package aula;

public class App {
    

    public static void main(String[] args) {

        Aviao aviao = new Aviao(10, 10, 5, 5, 6);

        System.out.println(aviao.acelerar(5));

        aviao.ligarAviao();

        aviao.viagem();

        System.out.println(String.format("O consumo de combustivel nessa viagem foi de %d Litros, com %d tripulantes, %d passageiros, com um peso total de %d", aviao.acelerar(6), aviao.getTripulante(), aviao.getPassageiro(), aviao.getPeso()));

    

    }
}
