/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Scanner;

public class App {



    public static void main(String[] args) {
        //3..10
        //
        Scanner scaner = new Scanner(System.in);


        int teclado;
        do {
            System.out.print("Qual o tamanho da matriz? (3..10) ");
            teclado = scaner.nextInt();
            
        } while (teclado < 3 || teclado > 10);

        int[][] matriz = new int[teclado][teclado];

        for (int i = 0; i < teclado; i++) {
            for (int j = 0; j < teclado; j++) {
                if (i == j) {
                    matriz[i][j] = 1;
                }
                System.out.printf(matriz[i][j] + " ");
            }
            System.out.println();
        }
    }

}
