/*
 * This source file was generated by the Gradle 'init' task
 */
package aula;

import java.util.ArrayList;


public class App {

    



    public static void main(String[] args) {
        ArrayList<String> lista = new ArrayList<>();
        ArrayList<Pessoa> agenda = new ArrayList<>();

        lista.add("POO");
        lista.add("EDC");
        lista.add("MTM");
        lista.add("PFF");

        Pessoa pessoa = new Pessoa("Nicolas", "nicolas@gmail.com");
        Pessoa pessoa2 = new Pessoa("Lucas", "joao@gmail.com");
        Pessoa pessoa3 = new Pessoa("Raphael", "raphael@gmail.com");
        Pessoa pessoa4 = new Pessoa("Leonardo", "Leo@gmail.com");

        agenda.add(pessoa);
        agenda.add(pessoa2);
        agenda.add(pessoa3);
        agenda.add(pessoa4);

        for (String elemento : lista) {
            System.out.println(elemento);
        }

        lista.forEach(elemento -> {
            System.out.println(elemento);
        });

        lista.forEach(System.out::println);

        agenda.forEach(System.out::println);

        lista.removeIf(element -> element.equals("POO"));

        lista.forEach(System.out::println);

        agenda.removeIf(element -> element.getNome() == "Nicolas");

        agenda.forEach(System.out::println);


    }
}
