/*
 * This source file was generated by the Gradle 'init' task
 */
package aula;

import main.java.aula.Caneta;

public class App {
    
    public static void main(String[] args) {
        
        Caneta bic = new Caneta();

        bic.definirCor("Branca");

        System.out.println(bic.isAberta());
        bic.abrirFechar();
        System.out.println(bic.isAberta());
    
        System.out.println(bic.qualCor());
        bic.definirCor("Vermelho");
        System.out.println(bic.qualCor());
    }


}
