/*
 * This source file was generated by the Gradle 'init' task
 */
package aula;

import main.java.aula.*;

public class App {
    
    public static void main(String[] args) {
        
        Caneta bic = new Caneta();

        bic.definirCor("Branca");

        bic.registrarTinta(100);
        bic.obterTinta();
        bic.abrirFechar();
        bic.isAberta();

        System.out.println(bic.desenhar(5));
        System.out.println(bic.desenhar(7));
        System.out.println(bic.desenhar(-1));
        bic.obterTinta();
    }


}
